version: '1.0'
services:
  web:
    container_name: fastapi_app
    build: .
    ports:
      - "7000:8000"
    volumes:
      - .:/app
      - /sessions:/app/sessions
    depends_on:
      - redis
  
  worker:
    build: .
    container_name: celery_worker
    command: ["sh", "-c", "chmod +x ./celery_worker.sh && ./celery_worker.sh"]
    volumes:
      - .:/app
      - /sessions:/app/sessions
    depends_on:
      - redis

  redis:
    container_name: redis_container
    image: redis:latest
    ports:
      - "6379:6379"
